### ISSUE TITLE
Potential style change.

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/tbranyen.com#7]
``` css
header {
  background: #FFFFFF;
  color: #858585;
  border-bottom: 3px solid #E5F2FF;
}

header a {
  color: #808080;
}
```
